[package]
name = "rust-ardanlabs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]
members = [
    "session1/hello_world", 
    "session1/variables",
    "session1/authentication", 
    "session1/login", 
    "session1/login_manager", 
    "session2/hello",
    "session2/divide_work",
    "session2/thread_builder",
    "session2/scoped_threads",
    "session2/footgun",
    "session2/mutexes",
    "session2/rwlocks",
    "session2/deadlocks",
    "session2/dashing",
    "session2/parking",
    "session2/channels",
    "session2/workers",
    #threadpool -> workers2
    "session2/threadpool",
    "session2/affinity",
    "session2/tprio",
    "session3/hello_async",
    "session3/hello_tokio",
    "session3/blocking",
    "session3/tokio_testing",
    "session3/errors",
    "session3/fileio",
    "session3/restclient",
    "session3/tcpserver",
    "session3/async_channels",
    "session3/async_mutex",
    "session3/tokio_select",
    "session3/tokio_select_broadcast",
    "session3/pinning",
    "session4/logspan",
]
