[package]
name = "errors"
version = "0.1.0"
edition = "2021"

[dependencies]
authentication = { path = "../../session1/authentication" }
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.11"
